n = input('\033[1;34mDigite Algo:')
a = n.isnumeric()
b = n.isalpha()
c = n.isspace()
d = n.isalnum()
e = n.isupper()
f = n.islower()
g = n.istitle()
print('\033[0;31mO tipo primitivo é {}.'.format(type(n)))
print('\033[0;32mÉ numérico?{}'.format(a))
print('\033[0;33mÉ alfabético?{}'.format(b))
print('\033[0;34mSó tem espaços?{}'.format(c))
print('\033[0;35mÉ alfanumérico?{}'.format(d))
print('\033[0;36mEstá em maiusculas?{}'.format(e))
print('\033[0;31mEstá em minuscuslas?{}'.format(f))
print('\033[0;32mEstá capitalizada?{}'.format(g))
